name: Deploy Frontend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL != '' && vars.VITE_API_BASE_URL || secrets.VITE_API_BASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      S3_BUCKET: ${{ vars.S3_BUCKET != '' && vars.S3_BUCKET || secrets.S3_BUCKET }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION != '' && vars.AWS_DEFAULT_REGION || 'sa-east-1' }}
      CLOUDFRONT_DIST_ID: ${{ vars.CLOUDFRONT_DIST_ID != '' && vars.CLOUDFRONT_DIST_ID || secrets.CLOUDFRONT_DIST_ID }}
    steps:
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: dist

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Sync to S3
        run: aws s3 sync dist/ s3://${{ vars.S3_BUCKET }}/ --delete

      - name: Invalidate CloudFront
        if: ${{ vars.CLOUDFRONT_DIST_ID != '' }}
        run: aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT_DIST_ID }} --paths "/*"


